import NavBar from "@/components/Navbar/Navbar";
import "./globals.scss";
import { Oswald } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeContext/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Anime Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <ThemeProvider>
          <AuthProvider>
            <NavBar />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
